package ue1104.iramps.be.Servlet;

public enum EnumAPIOperation {
    GET_BY_ID,
    GET_BY_PARAM,
    GET_PERSONNE_COURS_MULTI,
    GET_PERSONNE_COURS_ONE,
    CREATE,
    CREATE_PERSONNE_COURS,
    UPDATE,
    UPDATE_PERSONNE_COURS,
    UPDATE_MULTI,
    UPDATE_SECTION_COURS,
    UPDATE_STATUS_PERSONNE,
    DELETE_ONE,
    DELETE_MULTI,
    DELETE_PERSONNE_COURS,
}
